### ISSUE TITLE
python 3.5

### ISSUE THREAD

**Issue by JamiePringle** [IQuOD/wodpy#13]
I am having issues using wodpy with python 3.5; is this supposed to work? 
If yes, I will try to debug. 
If no, I will read the data in python 2.7. 

Cheers,
and thanks for this tool,
Jamie Pringle
University of New Hampshire

**Comment by katieannemills** [comment]
Thanks for getting in touch! Python 3.4 is *supposed* to work (famous last words), and I'd like to at least consider supporting 3.5 if it isn't a huge rabbit-hole (if it *is* a huge rabbit hole, we can still do it - but it might have to wait until I have some downtime :). Why don't you post your error, and we'll have a look.

**Comment by JamiePringle** [comment]
To duplicate the error, run the following code with the attached WODS file that I created in November 2016

```
from wodpy import wod
fid=open('ocldb1480519285.28325.APB','r')
profile1=wod.WodProfile(fid)
profile2=wod.WodProfile(fid)
```


I installed the two pythons in a clean anaconda install with "conda create -n py27 python=2.7 anaconda" and "conda create -n py35 python=3.5 anaconda" and I installed wodpy with "pip install wodpy" On December 1, 2016. Pip reported that it installed wodpy-1.3.0

In python 2.7, there are no errors. In python 3.5 the line "profile2=wod.WodProfile(fid)" dies with the following error

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/Users/pringle/workfiles/WODS_Dec2016/readdata/triggerBug.py in <module>()
      7 fid=open('ocldb1480519285.28325.APB','r')
      8 profile1=wod.WodProfile(fid)
----> 9 profile2=wod.WodProfile(fid)
     10 

/Users/pringle/anaconda/envs/py35/lib/python3.5/site-packages/wodpy/wod.py in __init__(self, fid, load_profile_data)
     46 
     47         # Read the various sections of the profile record.
---> 48         self._read_primary_header(fid)
     49         self._read_character_data_and_principal_investigator(fid)
     50         self._read_secondary_or_biological_header(fid)

/Users/pringle/anaconda/envs/py35/lib/python3.5/site-packages/wodpy/wod.py in _read_primary_header(self, fid)
    169         primary_header = {}
    170 
--> 171         self._interpret_data(fid, prhFormat, primary_header)
    172         # Now read variable specific metadata.
    173         primary_header['variables'] = []

/Users/pringle/anaconda/envs/py35/lib/python3.5/site-packages/wodpy/wod.py in _interpret_data(self, fid, format, dest)
    100 
    101             # Cast to the required data type.
--> 102             value = item[2](chars)
    103 
    104             # Check for special items otherwise store the data

ValueError: invalid literal for int() with base 10: ' '
```

The same error occurs on the second call to WodProfile() with other WODS files. 

Let me know if I can help you with anything,
thanks,
Jamie

[ocldb1480519285.28325.APB.zip](https://github.com/IQuOD/wodpy/files/624905/ocldb1480519285.28325.APB.zip)

**Comment by katieannemills** [comment]
Update: tracked this down to newline behavior in 2.x vs 3.x; [see this for a primer](http://stackoverflow.com/questions/4599936/handling-r-n-vs-n-newlines-in-python-on-mac-vs-windows). Basically, 3.x automatically homogenizes newline characters, whereas to get the same behavior in 2.x, `open` needs the `U` flag, like `fid=open('ocldb1480519285.28325.APB','rU')`. Then in principle we don't have to fiddle with line endings by hand, and it seems that the correct line length (at least on my mac) to use in `_calculate_next_profile_position` is 82 (which is where this problem was coming from - with the wrong line ending, your example was miscalculating where the profile ends in the file, and thinking it started in the middle of the whitespace at the end of the first profile).

Anyway, the likely fix is to open files with `U` and fix the line length multiplier to 82; but before I actually commit this, I need to think a bit about why 82, and double check that this doesn't break on windows. I'll keep you updated,

**Comment by JamiePringle** [comment]
Thanks.

**Comment by katieannemills** [comment]
This is resolved in #16, and will ship in tag 1.4.0 by the new year. Thanks for pointing this out!

**Comment by JamiePringle** [comment]
no worries, and thanks for fixing it!

**Comment by katieannemills** [comment]
Alright, 1.4.0 is posted to pypi and should solve this issue - let me know if it still doesn't work for you after upgrading.

**Comment by JamiePringle** [comment]
1.4.0 passed the tests I had. thanks!
Jamie
